export const SET_WEATHER = 'SET_WEATHER'
export const SET_FORECAST = 'SET_FORECAST'
export const SET_MAPS = 'SET_MAPS'
export const SET_ADCODE = 'SET_ADCODE'
export const SET_CENTER = 'SET_CENTER'
export const SET_TARGET = 'SET_TARGET'
export const SET_TARGET_NAME = 'SET_TARGET_NAME'
